"use client";

import { Inter } from "next/font/google";
import "../Scss/globals.scss";

import Header from "./Header.jsx";

// head import section
import Favicon from "../app/favicon.png";

// bootstrap connect
import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "@/components/ClientComponent.jsx";

// context api
import { ContextProvider, Context } from "@/components/ClientComponent.jsx";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Todo-App",
//   description: "Generated by Arham ullah khan",
//   icons: [{ rel: "icon", url: Favicon.src }],
// };
import { useState } from "react";
export default function RootLayout({ children }) {
  const [user, setUser] = useState({});
  return (
    <html lang="en">
      <head></head>

      <body>
        <BootstrapClient /> <Header />
        <Context.Provider value={(user, setUser)}>{children}</Context.Provider>
      </body>
    </html>
  );
}
